"""
tasks_exp7_stable.py — Filtered task set.

Auto-generated by run_stability_screen.py.
Contains only STABLE pairs from tasks_exp7.py.
Do not edit after stress sweep begins.
"""

from tasks_exp7 import (
    SA1,
    SA3,
    SA4,
    DE1,
    DE2,
    DE3,
    AC1,
    AC2,
)

PAIRS = [
    SA1,
    SA3,
    SA4,
    DE1,
    DE2,
    DE3,
    AC1,
    AC2,
]
