"""
tasks_exp5_stable.py — Filtered task set.

Auto-generated by run_stability_screen.py.
Contains only STABLE pairs from tasks_exp5.py.
Do not edit after stress sweep begins.
"""

from tasks_exp5 import (
    FA1,
    FA2,
    FA3,
    FA4,
    FB1,
    FB4,
    FC1,
    FC4,
    FD1,
    FD2,
    AC1,
    AC2,
    NC1,
)

PAIRS = [
    FA1,
    FA2,
    FA3,
    FA4,
    FB1,
    FB4,
    FC1,
    FC4,
    FD1,
    FD2,
    AC1,
    AC2,
    NC1,
]
