"""
tasks_exp3.py — Filtered task set for Experiment 3.

Auto-generated by run_stability_screen.py.
Contains only STABLE pairs from tasks_exp2.py.
Do not edit after stress sweep begins.
"""

from tasks_exp2 import (
    FA1,
    FA4,
    FB1,
    FB4,
    FC1,
    FC4,
    FD1,
    FD2,
    FD4,
    AC1,
    AC2,
    NC1,
)

PAIRS = [
    FA1,
    FA4,
    FB1,
    FB4,
    FC1,
    FC4,
    FD1,
    FD2,
    FD4,
    AC1,
    AC2,
    NC1,
]
