"""
tasks_exp6_stable.py — Filtered task set.

Auto-generated by run_stability_screen.py.
Contains only STABLE pairs from tasks_exp6.py.
Do not edit after stress sweep begins.
"""

from tasks_exp6 import (
    SA2,
    SA3,
    SA7,
    DE1,
    DE2,
    AC2,
)

PAIRS = [
    SA2,
    SA3,
    SA7,
    DE1,
    DE2,
    AC2,
]
